//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Carrito
    {
        public int IDCarrito { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<int> IDProducto { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public Nullable<int> Cantidad { get; set; }
        [Required(ErrorMessage = "El {0} es requerido")]
        [Range(0.01, double.MaxValue, ErrorMessage = "El {0} debe ser mayor que cero")]
        public Nullable<decimal> Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
