//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Factura
    {
        public int IDFactura { get; set; }
        public Nullable<int> IDPedido { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }

        public string DetallesFactura { get; set; }

        
        public virtual Pedido Pedido { get; set; }
    }
}
